### ISSUE TITLE
大佬能实现一个java语言的吗

### ISSUE THREAD

**Issue by GFL0614** [xuqingquan1995/M3U8Downloader#1]

**Comment by xuqingquan1995** [comment]
应你要求，我会在近期实现一个做一个同样功能的java版本

**Comment by xuqingquan1995** [comment]
应你要求，我会在近期实现一个做一个同样功能的java版本 @GFL0614

**Comment by GFL0614** [comment]
> 应你要求，我会在近期实现一个做一个同样功能的java版本@ GFL0614

谢谢 之前改了start最高的那个m3u8download 但是总感觉还是不太好用 主要是对于多任务这块

**Comment by GFL0614** [comment]
大佬  java版本大概多久会出来

**Comment by xuqingquan1995** [comment]
请稍等，我会在这个周六周天里做出来

**Comment by xuqingquan1995** [comment]
已使用Java进行实现，并将下载库更换为Aria，Aria将更方便进行M3U8的下载，谢谢关注 @GFL0614
