### ISSUE TITLE
请问怎么联系到你呢，我这m3u8的视频是带key的，下载下来播放不了

### ISSUE THREAD

**Issue by ZeroYaw** [xuqingquan1995/M3U8Downloader#2]

**Comment by xuqingquan1995** [comment]
可以把链接给我看一下么？

**Comment by ZeroYaw** [comment]
&nbsp;


&nbsp;https://v01-gl-vod.dtslb.com/201912/04/GtdwxZzt/800kb/hls/index.m3u8
谢谢啊，我找到解决办法了，把前面的key文件下载到同一个目录下就行了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"许清泉"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午2:29
收件人:&nbsp;"xuqingquan1995/M3U8Downloader"<M3U8Downloader@noreply.github.com&gt;;
抄送:&nbsp;"⑨o后、孤寡老人"<1226848371@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuqingquan1995/M3U8Downloader] 请问怎么联系到你呢，我这m3u8的视频是带key的，下载下来播放不了 (#2)




可以把链接给我看一下么？
