### ISSUE TITLE
没有ts下载合并吗

### ISSUE THREAD

**Issue by GXSZone** [xuqingquan1995/M3U8Downloader#3]
https://v1.szjal.cn/20190819/Ql6UD1od/index.m3u8另外这种链接也不支持

**Comment by xuqingquan1995** [comment]
应该是有支持的呢，有添加这种规则的判断哩

**Comment by xuqingquan1995** [comment]
ts 合并可以通过调用系统命令cat file1 file2 ... > file 实现，这是在linux系上最简单的实现方式了

**Comment by GXSZone** [comment]
试了下，打印出来的解析后的链接不对

**Comment by xuqingquan1995** [comment]
能给我看下你的执行的日志么

**Comment by GXSZone** [comment]
这种连接` https://v2.szjal.cn/20200202/7YbvfirZ/index.m3u8`最后是这样的
      `https://v2.szjal.cn/ppvod/32F6D6FCC42C2CD16C97DF44735E0553.m3u8`

**Comment by GXSZone** [comment]
@xuqingquan1995 这个链接也不行
`https://hls.aoxtv.com/v1.szjal.cn/20200407/wxd37w0d/index.m3u8`

**Comment by cqpsjsl** [comment]
python 文件名过长，OSError: [Errno 36] File name too long: './downloads/03000500005DF9C3EE705C06CCEAA89808F3E0-A84A-4AFA-B231-CA0FCF28A353-00004.ts?ccode=0512&duration=2568&expire=18000&psid=84c588703f690d5afc1d11b3a5827668&ups_client_netip=b2ec2bb6&ups_ts=1589885867&ups_userid=1030653830&utid=q6lKFxWoGBACAbLsK7btIl%2B5&vid=XNDQ3MzczNjYwMA%3D%3D&s=5a757c1f951b4fec9a6a&iv=1&sp=&bc=2&si=3&eo=1&vkey=B549c7ca3a8815de2782b3d1ade7b7ebe\r

**Comment by cuba3** [comment]
@cqpsjsl > python 文件名过长，OSError: [Errno 36] File name too long: './downloads/03000500005DF9C3EE705C06CCEAA89808F3E0-A84A-4AFA-B231-CA0FCF28A353-00004.ts?ccode=0512&duration=2568&expire=18000&psid=84c588703f690d5afc1d11b3a5827668&ups_client_netip=b2ec2bb6&ups_ts=1589885867&ups_userid=1030653830&utid=q6lKFxWoGBACAbLsK7btIl%2B5&vid=XNDQ3MzczNjYwMA%3D%3D&s=5a757c1f951b4fec9a6a&iv=1&sp=&bc=2&si=3&eo=1&vkey=B549c7ca3a8815de2782b3d1ade7b7ebe\r

什么m3u8地址给我看看？后面那串是什么秘钥加密的吧……

**Comment by cqpsjsl** [comment]
https://ykm3u8.0ju.cc/data/youku/XNDQ1OTc1MDY5Ng==.m3u8

**Comment by cuba3** [comment]
@cqpsjsl > https://ykm3u8.0ju.cc/data/youku/XNDQ1OTc1MDY5Ng==.m3u8
已升级支持超长ts url 下载 ，你给的这个ts长达 424字符，request穿了，改用params就好了

相关代码段
# 修改request模式为 url + params ,支持超长request
                            p = urllib.parse.urlparse(pdUrl)
                            u = p.scheme + '://' + p.netloc + p.path
                            pTemp = urllib.parse.parse_qs(p.query)
                            for i in pTemp:
                                pTemp[i] = pTemp[i][0]
